name: Build and Deploy to Appetize

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      # Compiles the simulator application directory (.app)x
      - name: Build iOS Simulator App
        run: ./gradlew :shared:iosX64Binaries

      # Zips the built .app package so Appetize can read it
      - name: Zip Simulator App
        run: |
          cd shared/build/bin/iosX64/debugFramework/
          zip -r iosApp.zip *.framework

      # Uploads the zip directly to your Appetize dashboard
      - name: Upload to Appetize.io
        run: |
          curl --url "https://appetize.io" \
               --user "${{ secrets.APPETIZE_API_TOKEN }}:" \
               --form "file=@shared/build/bin/iosX64/debugFramework/iosApp.zip" \
               --form "platform=ios"
