name: Build iOS App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ios:
    runs-on: macos-14 # Uses a macOS environment with Xcode pre-installed Minor Change
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Gradle Cache
      uses: gradle/actions/setup-gradle@v3

    - name: Build iOS Framework / App
      run: ./gradlew :composeApp:iosX64Binaries # Compiles the iOS simulator binary
